/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.hdsb.gwss.elliex.ics3u.u5;

import static ca.hdsb.gwss.elliex.ics3u.other.SOPL.sopl;

/**
 *
 * @author 1xuell
 */
public class MasterMind extends javax.swing.JFrame {

    static int correctColor = 0;
    static int correctPosition = 0;
    String block1 = "";
    String block2 = "";
    String block3 = "";

    /**
     * Creates new form MasterMind
     */
    public MasterMind() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guess1 = new javax.swing.JTextField();
        guess2 = new javax.swing.JTextField();
        guess3 = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        newgame = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        colours = new javax.swing.JLabel();
        positions = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Guess the Colour of the Blocks");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your guesses:");

        guess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guess1ActionPerformed(evt);
            }
        });

        guess2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guess2ActionPerformed(evt);
            }
        });

        guess3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guess3ActionPerformed(evt);
            }
        });

        check.setText("Check your Answer");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        newgame.setText("New Game");
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });

        jLabel3.setText("Number of Colours correct:");

        jLabel4.setText("Number of Posistions correct:");

        colours.setText(" ");

        positions.setText(" ");

        jLabel5.setText("R, G, B, Y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(check)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(guess1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(55, 55, 55)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(guess3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(guess2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(positions, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(37, 37, 37)
                                            .addComponent(colours, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newgame)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guess1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(colours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(positions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newgame)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guess1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guess1ActionPerformed

    private void guess2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guess2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guess2ActionPerformed

    private void guess3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guess3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guess3ActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        String answer1 = guess1.getText();
        String answer2 = guess2.getText();
        String answer3 = guess3.getText();
        sopl(block1 + block2 + block2);
        if (answer1.equalsIgnoreCase(block1)) {
            correctPosition++;
        }
        if (answer2.equalsIgnoreCase(block2)) {
            correctPosition++;
        }
        if (answer3.equalsIgnoreCase(block3)) {
            correctPosition++;
        }
        if (answer1.equalsIgnoreCase(block1) || answer1.equalsIgnoreCase(block2) || answer1.equalsIgnoreCase(block3)) {
            correctColor++;
            sopl("1: " + correctColor);
        }
        if (answer2.equalsIgnoreCase(block1) || answer2.equalsIgnoreCase(block2) || answer2.equalsIgnoreCase(block3)) {
            correctColor++;
            sopl("2: " + correctColor);
        }
        if (answer3.equalsIgnoreCase(block1) || answer3.equalsIgnoreCase(block2) || answer3.equalsIgnoreCase(block3)) {
            correctColor++;
            sopl("3: " + correctColor);
        }
        sopl(correctColor);
        sopl(correctPosition);
        colours.setText(Integer.toString(correctColor));
        positions.setText(Integer.toString(correctPosition));
    }//GEN-LAST:event_checkActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        int colour1 = (int) (Math.random() * 4) + 1;
        switch (colour1) {
            case 1:
                block1 = "R";
                break;
            case 2:
                block1 = "Y";
                break;
            case 3:
                block1 = "B";
                break;
            case 4:
                block1 = "G";
        }
        int colour2 = (int) (Math.random() * 4) + 1;
        switch (colour2) {
            case 1:
                block2 = "R";
                break;
            case 2:
                block2 = "Y";
                break;
            case 3:
                block2 = "B";
                break;
            case 4:
                block2 = "G";
        }
        int colour3 = (int) (Math.random() * 4) + 1;
        switch (colour3) {
            case 1:
                block3 = "R";
                break;
            case 2:
                block3 = "Y";
                break;
            case 3:
                block3 = "B";
                break;
            case 4:
                block3 = "G";
        }
        
    }//GEN-LAST:event_newgameActionPerformed
    private void checkActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String answer1 = guess1.getText();
        String answer2 = guess2.getText();
        String answer3 = guess3.getText();
        sopl(block1 + block2 + block2);
        if (answer1.equalsIgnoreCase(block1)) {
            correctPosition++;
        }
        if (answer2.equalsIgnoreCase(block2)) {
            correctPosition++;
        }
        if (answer3.equalsIgnoreCase(block3)) {
            correctPosition++;
        }
        if (answer1.equalsIgnoreCase(block1) || answer1.equalsIgnoreCase(block2) || answer1.equalsIgnoreCase(block3)) {
            correctColor++;
            sopl("1: " + correctColor);
        }
        if (answer2.equalsIgnoreCase(block1) || answer2.equalsIgnoreCase(block2) || answer2.equalsIgnoreCase(block3)) {
            correctColor++;
            sopl("2: " + correctColor);
        }
        if (answer3.equalsIgnoreCase(block1) || answer3.equalsIgnoreCase(block2) || answer3.equalsIgnoreCase(block3)) {
            correctColor++;
            sopl("3: " + correctColor);
        }
        sopl(correctColor);
        sopl(correctPosition);
        colours.setText(Integer.toString(correctColor));
        positions.setText(Integer.toString(correctPosition));
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterMind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check;
    private javax.swing.JLabel colours;
    private javax.swing.JTextField guess1;
    private javax.swing.JTextField guess2;
    private javax.swing.JTextField guess3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newgame;
    private javax.swing.JLabel positions;
    // End of variables declaration//GEN-END:variables
}
